name: refridge
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  firebase_messaging: ^15.0.4
  firebase_remote_config: ^5.0.4
  firebase_storage: ^12.1.3
  google_sign_in: ^6.2.1
  http: ^1.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  shared_preferences: ^2.3.1
  provider: ^6.1.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.1.0
  intl: ^0.19.0
  scroll_date_picker: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.12
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/app_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/groceries/
    - assets/app_icon/
    - assets/logos/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeueRoman.otf
          style: normal
        - asset: assets/fonts/HelveticaNeueItalic.ttf
          style: italic
        - asset: assets/fonts/HelveticaNeueUltraLight.otf
          style: normal
          weight: 100
        - asset: assets/fonts/HelveticaNeueUltraLightItalic.otf
          style: italic
          weight: 100
        - asset: assets/fonts/HelveticaNeueThin.otf
          style: normal
          weight: 200
        - asset: assets/fonts/HelveticaNeueThinItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/HelveticaNeueLight.otf
          style: normal
          weight: 300
        - asset: assets/fonts/HelveticaNeueLightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/HelveticaNeueMedium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/HelveticaNeueMediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/HelveticaNeueBold.otf
          style: normal
          weight: 600
        - asset: assets/fonts/HelveticaNeueBoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/HelveticaNeueHeavy.otf
          style: normal
          weight: 700
        - asset: assets/fonts/HelveticaNeueHeavyItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/HelveticaNeueBlack.otf
          style: normal
          weight: 800
        - asset: assets/fonts/HelveticaNeueBlackItalic.otf
          style: italic
          weight: 800

