import 'package:flutter/material.dart';
import 'package:refridge/src/domain/models/grocery.dart';
import 'package:refridge/src/domain/models/grocery_template.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension GroceryTemplateExt on GroceryTemplate {
  String getLabel(BuildContext context) {
    switch (id) {
      case "1":
        return AppLocalizations.of(context)!.grocery_apple;
      case "2":
        return AppLocalizations.of(context)!.grocery_banana;
      case "3":
        return AppLocalizations.of(context)!.grocery_orange;
      case "4":
        return AppLocalizations.of(context)!.grocery_grapes;
      case "5":
        return AppLocalizations.of(context)!.grocery_berries;
      case "6":
        return AppLocalizations.of(context)!.grocery_melon;
      case "7":
        return AppLocalizations.of(context)!.grocery_mango;
      case "8":
        return AppLocalizations.of(context)!.grocery_pineapple;
      case "9":
        return AppLocalizations.of(context)!.grocery_lemon;
      case "10":
        return AppLocalizations.of(context)!.grocery_lime;
      case "11":
        return AppLocalizations.of(context)!.grocery_avocado;
      case "12":
        return AppLocalizations.of(context)!.grocery_pear;
      case "13":
        return AppLocalizations.of(context)!.grocery_peach;
      case "14":
        return AppLocalizations.of(context)!.grocery_plum;
      case "15":
        return AppLocalizations.of(context)!.grocery_cherry;
      case "16":
        return AppLocalizations.of(context)!.grocery_kiwi;
      case "17":
        return AppLocalizations.of(context)!.grocery_pomegranate;
      case "18":
        return AppLocalizations.of(context)!.grocery_carrot;
      case "19":
        return AppLocalizations.of(context)!.grocery_potato;
      case "20":
        return AppLocalizations.of(context)!.grocery_sweet_potato;
      case "21":
        return AppLocalizations.of(context)!.grocery_tomato;
      case "22":
        return AppLocalizations.of(context)!.grocery_cucumber;
      case "23":
        return AppLocalizations.of(context)!.grocery_lettuce;
      case "24":
        return AppLocalizations.of(context)!.grocery_spinach;
      case "25":
        return AppLocalizations.of(context)!.grocery_kale;
      case "26":
        return AppLocalizations.of(context)!.grocery_broccoli;
      case "27":
        return AppLocalizations.of(context)!.grocery_cauliflower;
      case "28":
        return AppLocalizations.of(context)!.grocery_bell_pepper;
      case "29":
        return AppLocalizations.of(context)!.grocery_onion;
      case "30":
        return AppLocalizations.of(context)!.grocery_garlic;
      case "31":
        return AppLocalizations.of(context)!.grocery_mushroom;
      case "32":
        return AppLocalizations.of(context)!.grocery_zucchini;
      case "33":
        return AppLocalizations.of(context)!.grocery_eggplant;
      case "34":
        return AppLocalizations.of(context)!.grocery_asparagus;
      case "35":
        return AppLocalizations.of(context)!.grocery_brussels_sprouts;
      case "36":
        return AppLocalizations.of(context)!.grocery_green_beans;
      case "37":
        return AppLocalizations.of(context)!.grocery_cabbage;
      case "38":
        return AppLocalizations.of(context)!.grocery_milk;
      case "39":
        return AppLocalizations.of(context)!.grocery_cheese;
      case "40":
        return AppLocalizations.of(context)!.grocery_yogurt;
      case "41":
        return AppLocalizations.of(context)!.grocery_butter;
      case "42":
        return AppLocalizations.of(context)!.grocery_cream;
      case "43":
        return AppLocalizations.of(context)!.grocery_eggs;
      case "44":
        return AppLocalizations.of(context)!.grocery_chicken;
      case "45":
        return AppLocalizations.of(context)!.grocery_beef;
      case "46":
        return AppLocalizations.of(context)!.grocery_pork;
      case "47":
        return AppLocalizations.of(context)!.grocery_lamb;
      case "48":
        return AppLocalizations.of(context)!.grocery_turkey;
      case "49":
        return AppLocalizations.of(context)!.grocery_salmon;
      case "50":
        return AppLocalizations.of(context)!.grocery_tuna;
      case "51":
        return AppLocalizations.of(context)!.grocery_shrimp;
      case "52":
        return AppLocalizations.of(context)!.grocery_cod;
      case "53":
        return AppLocalizations.of(context)!.grocery_crab;
      case "54":
        return AppLocalizations.of(context)!.grocery_lobster;
      case "55":
        return AppLocalizations.of(context)!.grocery_scallops;
      case "56":
        return AppLocalizations.of(context)!.grocery_tilapia;
      case "57":
        return AppLocalizations.of(context)!.grocery_sardines;
      case "58":
        return AppLocalizations.of(context)!.grocery_oysters;
      case "59":
        return AppLocalizations.of(context)!.grocery_bread;
      case "60":
        return AppLocalizations.of(context)!.grocery_rice;
      case "61":
        return AppLocalizations.of(context)!.grocery_pasta;
      case "62":
        return AppLocalizations.of(context)!.grocery_oats;
      case "63":
        return AppLocalizations.of(context)!.grocery_quinoa;
      case "64":
        return AppLocalizations.of(context)!.grocery_tortillas;
      case "65":
        return AppLocalizations.of(context)!.grocery_flour;
      case "66":
        return AppLocalizations.of(context)!.grocery_sugar;
      case "67":
        return AppLocalizations.of(context)!.grocery_baking_soda;
      case "68":
        return AppLocalizations.of(context)!.grocery_baking_powder;
      case "69":
        return AppLocalizations.of(context)!.grocery_salt;
      case "70":
        return AppLocalizations.of(context)!.grocery_oil;
      case "71":
        return AppLocalizations.of(context)!.grocery_vinegar;
      case "72":
        return AppLocalizations.of(context)!.grocery_honey;
      case "73":
        return AppLocalizations.of(context)!.grocery_maple_syrup;
      case "74":
        return AppLocalizations.of(context)!.grocery_molasses;
      case "75":
        return AppLocalizations.of(context)!.grocery_spices;
      case "76":
        return AppLocalizations.of(context)!.grocery_canned_vegetables;
      case "77":
        return AppLocalizations.of(context)!.grocery_canned_fruits;
      case "78":
        return AppLocalizations.of(context)!.grocery_canned_beans;
      case "79":
        return AppLocalizations.of(context)!.grocery_canned_tomatoes;
      case "80":
        return AppLocalizations.of(context)!.grocery_soups;
      case "81":
        return AppLocalizations.of(context)!.grocery_sauces;
      case "82":
        return AppLocalizations.of(context)!.grocery_peanut_butter;
      case "83":
        return AppLocalizations.of(context)!.grocery_jam_jelly;
      case "84":
        return AppLocalizations.of(context)!.grocery_chips;
      case "85":
        return AppLocalizations.of(context)!.grocery_crackers;
      case "86":
        return AppLocalizations.of(context)!.grocery_cookies;
      case "87":
        return AppLocalizations.of(context)!.grocery_chocolate;
      case "88":
        return AppLocalizations.of(context)!.grocery_candy;
      case "89":
        return AppLocalizations.of(context)!.grocery_nuts;
      case "90":
        return AppLocalizations.of(context)!.grocery_popcorn;
      case "91":
        return AppLocalizations.of(context)!.grocery_coffee;
      case "92":
        return AppLocalizations.of(context)!.grocery_tea;
      case "93":
        return AppLocalizations.of(context)!.grocery_juice;
      case "94":
        return AppLocalizations.of(context)!.grocery_soda;
      case "95":
        return AppLocalizations.of(context)!.grocery_bottled_water;
      case "96":
        return AppLocalizations.of(context)!.grocery_sparkling_water;
      case "97":
        return AppLocalizations.of(context)!.grocery_frozen_vegetables;
      case "98":
        return AppLocalizations.of(context)!.grocery_frozen_fruits;
      case "99":
        return AppLocalizations.of(context)!.grocery_ice_cream;
      case "100":
        return AppLocalizations.of(context)!.grocery_frozen_dinners;
      case "101":
        return AppLocalizations.of(context)!.grocery_frozen_meats;
      case "102":
        return AppLocalizations.of(context)!.grocery_frozen_bread;
      case "103":
        return AppLocalizations.of(context)!.grocery_ketchup;
      case "104":
        return AppLocalizations.of(context)!.grocery_mustard;
      case "105":
        return AppLocalizations.of(context)!.grocery_mayonnaise;
      case "106":
        return AppLocalizations.of(context)!.grocery_salad_dressing;
      case "107":
        return AppLocalizations.of(context)!.grocery_hot_sauce;
      case "108":
        return AppLocalizations.of(context)!.grocery_bbq_sauce;
      case "109":
        return AppLocalizations.of(context)!.grocery_soy_sauce;
      case "110":
        return AppLocalizations.of(context)!.grocery_relish;
      case "111":
        return AppLocalizations.of(context)!.grocery_pickles;
      case "112":
        return AppLocalizations.of(context)!.grocery_salsa;
      case "113":
        return AppLocalizations.of(context)!.grocery_cereal;
      case "114":
        return AppLocalizations.of(context)!.grocery_pancake_waffle_mix;
      case "115":
        return AppLocalizations.of(context)!.grocery_syrup;
      case "116":
        return AppLocalizations.of(context)!.grocery_instant_oatmeal;
      case "117":
        return AppLocalizations.of(context)!.grocery_breakfast_bars;
      case "118":
        return AppLocalizations.of(context)!.grocery_bagels;
      case "119":
        return AppLocalizations.of(context)!.grocery_english_muffins;
      case "120":
        return AppLocalizations.of(context)!.grocery_paper_towels;
      case "121":
        return AppLocalizations.of(context)!.grocery_toilet_paper;
      case "122":
        return AppLocalizations.of(context)!.grocery_dish_soap;
      case "123":
        return AppLocalizations.of(context)!.grocery_laundry_detergent;
      case "124":
        return AppLocalizations.of(context)!.grocery_cleaning_supplies;
      case "125":
        return AppLocalizations.of(context)!.grocery_trash_bags;
      case "126":
        return AppLocalizations.of(context)!.grocery_aluminum_foil;
      case "127":
        return AppLocalizations.of(context)!.grocery_plastic_wrap;
      case "128":
        return AppLocalizations.of(context)!.grocery_napkins;
      case "129":
        return AppLocalizations.of(context)!.grocery_toothpaste;
      case "130":
        return AppLocalizations.of(context)!.grocery_shampoo;
      case "131":
        return AppLocalizations.of(context)!.grocery_conditioner;
      case "132":
        return AppLocalizations.of(context)!.grocery_soap;
      case "133":
        return AppLocalizations.of(context)!.grocery_deodorant;
      case "134":
        return AppLocalizations.of(context)!.grocery_lotion;
      case "135":
        return AppLocalizations.of(context)!.grocery_shaving_cream;
      case "136":
        return AppLocalizations.of(context)!.grocery_razors;
      case "137":
        return AppLocalizations.of(context)!.grocery_feminine_hygiene_products;
      case "138":
        return AppLocalizations.of(context)!.grocery_baby_care;
      case "139":
        return AppLocalizations.of(context)!.grocery_dog_food;
      case "140":
        return AppLocalizations.of(context)!.grocery_cat_food;
      case "141":
        return AppLocalizations.of(context)!.grocery_pet_treats;
      case "142":
        return AppLocalizations.of(context)!.grocery_kitty_litter;

      default:
        return AppLocalizations.of(context)!.account_screen_title;
    }
  }
}

extension GroceryExt on Grocery {
  String getLabel(BuildContext context) {
    switch (groceryId) {
      case "1":
        return AppLocalizations.of(context)!.grocery_apple;
      case "2":
        return AppLocalizations.of(context)!.grocery_banana;
      case "3":
        return AppLocalizations.of(context)!.grocery_orange;
      case "4":
        return AppLocalizations.of(context)!.grocery_grapes;
      case "5":
        return AppLocalizations.of(context)!.grocery_berries;
      case "6":
        return AppLocalizations.of(context)!.grocery_melon;
      case "7":
        return AppLocalizations.of(context)!.grocery_mango;
      case "8":
        return AppLocalizations.of(context)!.grocery_pineapple;
      case "9":
        return AppLocalizations.of(context)!.grocery_lemon;
      case "10":
        return AppLocalizations.of(context)!.grocery_lime;
      case "11":
        return AppLocalizations.of(context)!.grocery_avocado;
      case "12":
        return AppLocalizations.of(context)!.grocery_pear;
      case "13":
        return AppLocalizations.of(context)!.grocery_peach;
      case "14":
        return AppLocalizations.of(context)!.grocery_plum;
      case "15":
        return AppLocalizations.of(context)!.grocery_cherry;
      case "16":
        return AppLocalizations.of(context)!.grocery_kiwi;
      case "17":
        return AppLocalizations.of(context)!.grocery_pomegranate;
      case "18":
        return AppLocalizations.of(context)!.grocery_carrot;
      case "19":
        return AppLocalizations.of(context)!.grocery_potato;
      case "20":
        return AppLocalizations.of(context)!.grocery_sweet_potato;
      case "21":
        return AppLocalizations.of(context)!.grocery_tomato;
      case "22":
        return AppLocalizations.of(context)!.grocery_cucumber;
      case "23":
        return AppLocalizations.of(context)!.grocery_lettuce;
      case "24":
        return AppLocalizations.of(context)!.grocery_spinach;
      case "25":
        return AppLocalizations.of(context)!.grocery_kale;
      case "26":
        return AppLocalizations.of(context)!.grocery_broccoli;
      case "27":
        return AppLocalizations.of(context)!.grocery_cauliflower;
      case "28":
        return AppLocalizations.of(context)!.grocery_bell_pepper;
      case "29":
        return AppLocalizations.of(context)!.grocery_onion;
      case "30":
        return AppLocalizations.of(context)!.grocery_garlic;
      case "31":
        return AppLocalizations.of(context)!.grocery_mushroom;
      case "32":
        return AppLocalizations.of(context)!.grocery_zucchini;
      case "33":
        return AppLocalizations.of(context)!.grocery_eggplant;
      case "34":
        return AppLocalizations.of(context)!.grocery_asparagus;
      case "35":
        return AppLocalizations.of(context)!.grocery_brussels_sprouts;
      case "36":
        return AppLocalizations.of(context)!.grocery_green_beans;
      case "37":
        return AppLocalizations.of(context)!.grocery_cabbage;
      case "38":
        return AppLocalizations.of(context)!.grocery_milk;
      case "39":
        return AppLocalizations.of(context)!.grocery_cheese;
      case "40":
        return AppLocalizations.of(context)!.grocery_yogurt;
      case "41":
        return AppLocalizations.of(context)!.grocery_butter;
      case "42":
        return AppLocalizations.of(context)!.grocery_cream;
      case "43":
        return AppLocalizations.of(context)!.grocery_eggs;
      case "44":
        return AppLocalizations.of(context)!.grocery_chicken;
      case "45":
        return AppLocalizations.of(context)!.grocery_beef;
      case "46":
        return AppLocalizations.of(context)!.grocery_pork;
      case "47":
        return AppLocalizations.of(context)!.grocery_lamb;
      case "48":
        return AppLocalizations.of(context)!.grocery_turkey;
      case "49":
        return AppLocalizations.of(context)!.grocery_salmon;
      case "50":
        return AppLocalizations.of(context)!.grocery_tuna;
      case "51":
        return AppLocalizations.of(context)!.grocery_shrimp;
      case "52":
        return AppLocalizations.of(context)!.grocery_cod;
      case "53":
        return AppLocalizations.of(context)!.grocery_crab;
      case "54":
        return AppLocalizations.of(context)!.grocery_lobster;
      case "55":
        return AppLocalizations.of(context)!.grocery_scallops;
      case "56":
        return AppLocalizations.of(context)!.grocery_tilapia;
      case "57":
        return AppLocalizations.of(context)!.grocery_sardines;
      case "58":
        return AppLocalizations.of(context)!.grocery_oysters;
      case "59":
        return AppLocalizations.of(context)!.grocery_bread;
      case "60":
        return AppLocalizations.of(context)!.grocery_rice;
      case "61":
        return AppLocalizations.of(context)!.grocery_pasta;
      case "62":
        return AppLocalizations.of(context)!.grocery_oats;
      case "63":
        return AppLocalizations.of(context)!.grocery_quinoa;
      case "64":
        return AppLocalizations.of(context)!.grocery_tortillas;
      case "65":
        return AppLocalizations.of(context)!.grocery_flour;
      case "66":
        return AppLocalizations.of(context)!.grocery_sugar;
      case "67":
        return AppLocalizations.of(context)!.grocery_baking_soda;
      case "68":
        return AppLocalizations.of(context)!.grocery_baking_powder;
      case "69":
        return AppLocalizations.of(context)!.grocery_salt;
      case "70":
        return AppLocalizations.of(context)!.grocery_oil;
      case "71":
        return AppLocalizations.of(context)!.grocery_vinegar;
      case "72":
        return AppLocalizations.of(context)!.grocery_honey;
      case "73":
        return AppLocalizations.of(context)!.grocery_maple_syrup;
      case "74":
        return AppLocalizations.of(context)!.grocery_molasses;
      case "75":
        return AppLocalizations.of(context)!.grocery_spices;
      case "76":
        return AppLocalizations.of(context)!.grocery_canned_vegetables;
      case "77":
        return AppLocalizations.of(context)!.grocery_canned_fruits;
      case "78":
        return AppLocalizations.of(context)!.grocery_canned_beans;
      case "79":
        return AppLocalizations.of(context)!.grocery_canned_tomatoes;
      case "80":
        return AppLocalizations.of(context)!.grocery_soups;
      case "81":
        return AppLocalizations.of(context)!.grocery_sauces;
      case "82":
        return AppLocalizations.of(context)!.grocery_peanut_butter;
      case "83":
        return AppLocalizations.of(context)!.grocery_jam_jelly;
      case "84":
        return AppLocalizations.of(context)!.grocery_chips;
      case "85":
        return AppLocalizations.of(context)!.grocery_crackers;
      case "86":
        return AppLocalizations.of(context)!.grocery_cookies;
      case "87":
        return AppLocalizations.of(context)!.grocery_chocolate;
      case "88":
        return AppLocalizations.of(context)!.grocery_candy;
      case "89":
        return AppLocalizations.of(context)!.grocery_nuts;
      case "90":
        return AppLocalizations.of(context)!.grocery_popcorn;
      case "91":
        return AppLocalizations.of(context)!.grocery_coffee;
      case "92":
        return AppLocalizations.of(context)!.grocery_tea;
      case "93":
        return AppLocalizations.of(context)!.grocery_juice;
      case "94":
        return AppLocalizations.of(context)!.grocery_soda;
      case "95":
        return AppLocalizations.of(context)!.grocery_bottled_water;
      case "96":
        return AppLocalizations.of(context)!.grocery_sparkling_water;
      case "97":
        return AppLocalizations.of(context)!.grocery_frozen_vegetables;
      case "98":
        return AppLocalizations.of(context)!.grocery_frozen_fruits;
      case "99":
        return AppLocalizations.of(context)!.grocery_ice_cream;
      case "100":
        return AppLocalizations.of(context)!.grocery_frozen_dinners;
      case "101":
        return AppLocalizations.of(context)!.grocery_frozen_meats;
      case "102":
        return AppLocalizations.of(context)!.grocery_frozen_bread;
      case "103":
        return AppLocalizations.of(context)!.grocery_ketchup;
      case "104":
        return AppLocalizations.of(context)!.grocery_mustard;
      case "105":
        return AppLocalizations.of(context)!.grocery_mayonnaise;
      case "106":
        return AppLocalizations.of(context)!.grocery_salad_dressing;
      case "107":
        return AppLocalizations.of(context)!.grocery_hot_sauce;
      case "108":
        return AppLocalizations.of(context)!.grocery_bbq_sauce;
      case "109":
        return AppLocalizations.of(context)!.grocery_soy_sauce;
      case "110":
        return AppLocalizations.of(context)!.grocery_relish;
      case "111":
        return AppLocalizations.of(context)!.grocery_pickles;
      case "112":
        return AppLocalizations.of(context)!.grocery_salsa;
      case "113":
        return AppLocalizations.of(context)!.grocery_cereal;
      case "114":
        return AppLocalizations.of(context)!.grocery_pancake_waffle_mix;
      case "115":
        return AppLocalizations.of(context)!.grocery_syrup;
      case "116":
        return AppLocalizations.of(context)!.grocery_instant_oatmeal;
      case "117":
        return AppLocalizations.of(context)!.grocery_breakfast_bars;
      case "118":
        return AppLocalizations.of(context)!.grocery_bagels;
      case "119":
        return AppLocalizations.of(context)!.grocery_english_muffins;
      case "120":
        return AppLocalizations.of(context)!.grocery_paper_towels;
      case "121":
        return AppLocalizations.of(context)!.grocery_toilet_paper;
      case "122":
        return AppLocalizations.of(context)!.grocery_dish_soap;
      case "123":
        return AppLocalizations.of(context)!.grocery_laundry_detergent;
      case "124":
        return AppLocalizations.of(context)!.grocery_cleaning_supplies;
      case "125":
        return AppLocalizations.of(context)!.grocery_trash_bags;
      case "126":
        return AppLocalizations.of(context)!.grocery_aluminum_foil;
      case "127":
        return AppLocalizations.of(context)!.grocery_plastic_wrap;
      case "128":
        return AppLocalizations.of(context)!.grocery_napkins;
      case "129":
        return AppLocalizations.of(context)!.grocery_toothpaste;
      case "130":
        return AppLocalizations.of(context)!.grocery_shampoo;
      case "131":
        return AppLocalizations.of(context)!.grocery_conditioner;
      case "132":
        return AppLocalizations.of(context)!.grocery_soap;
      case "133":
        return AppLocalizations.of(context)!.grocery_deodorant;
      case "134":
        return AppLocalizations.of(context)!.grocery_lotion;
      case "135":
        return AppLocalizations.of(context)!.grocery_shaving_cream;
      case "136":
        return AppLocalizations.of(context)!.grocery_razors;
      case "137":
        return AppLocalizations.of(context)!.grocery_feminine_hygiene_products;
      case "138":
        return AppLocalizations.of(context)!.grocery_baby_care;
      case "139":
        return AppLocalizations.of(context)!.grocery_dog_food;
      case "140":
        return AppLocalizations.of(context)!.grocery_cat_food;
      case "141":
        return AppLocalizations.of(context)!.grocery_pet_treats;
      case "142":
        return AppLocalizations.of(context)!.grocery_kitty_litter;

      default:
        return AppLocalizations.of(context)!.account_screen_title;
    }
  }
}
